// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DataAccesLayer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageurifieldadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageurifieldadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201611041152015_image uri field added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
